/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PlanoProposta service. Represents a row in the &quot;PlanoProposta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.services.model.impl.PlanoPropostaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.services.model.impl.PlanoPropostaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlanoProposta
 * @generated
 */
@ProviderType
public interface PlanoPropostaModel extends BaseModel<PlanoProposta> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a plano proposta model instance should use the {@link PlanoProposta} interface instead.
	 */

	/**
	 * Returns the primary key of this plano proposta.
	 *
	 * @return the primary key of this plano proposta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this plano proposta.
	 *
	 * @param primaryKey the primary key of this plano proposta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this plano proposta.
	 *
	 * @return the ID of this plano proposta
	 */
	public long getId();

	/**
	 * Sets the ID of this plano proposta.
	 *
	 * @param id the ID of this plano proposta
	 */
	public void setId(long id);

	/**
	 * Returns the descricao of this plano proposta.
	 *
	 * @return the descricao of this plano proposta
	 */
	@AutoEscape
	public String getDescricao();

	/**
	 * Sets the descricao of this plano proposta.
	 *
	 * @param descricao the descricao of this plano proposta
	 */
	public void setDescricao(String descricao);

}