/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.services.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Proposta service. Represents a row in the &quot;Proposta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.services.model.impl.PropostaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.services.model.impl.PropostaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Proposta
 * @generated
 */
@ProviderType
public interface PropostaModel extends BaseModel<Proposta> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a proposta model instance should use the {@link Proposta} interface instead.
	 */

	/**
	 * Returns the primary key of this proposta.
	 *
	 * @return the primary key of this proposta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this proposta.
	 *
	 * @param primaryKey the primary key of this proposta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this proposta.
	 *
	 * @return the ID of this proposta
	 */
	public long getId();

	/**
	 * Sets the ID of this proposta.
	 *
	 * @param id the ID of this proposta
	 */
	public void setId(long id);

	/**
	 * Returns the nome_completo of this proposta.
	 *
	 * @return the nome_completo of this proposta
	 */
	@AutoEscape
	public String getNome_completo();

	/**
	 * Sets the nome_completo of this proposta.
	 *
	 * @param nome_completo the nome_completo of this proposta
	 */
	public void setNome_completo(String nome_completo);

	/**
	 * Returns the idade of this proposta.
	 *
	 * @return the idade of this proposta
	 */
	public Integer getIdade();

	/**
	 * Sets the idade of this proposta.
	 *
	 * @param idade the idade of this proposta
	 */
	public void setIdade(Integer idade);

	/**
	 * Returns the sexo of this proposta.
	 *
	 * @return the sexo of this proposta
	 */
	@AutoEscape
	public String getSexo();

	/**
	 * Sets the sexo of this proposta.
	 *
	 * @param sexo the sexo of this proposta
	 */
	public void setSexo(String sexo);

}