/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package br.com.services.model.impl;

import br.com.services.model.Proposta;
import br.com.services.model.PropostaModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Proposta service. Represents a row in the &quot;Proposta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>PropostaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PropostaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PropostaImpl
 * @generated
 */
@ProviderType
public class PropostaModelImpl
	extends BaseModelImpl<Proposta> implements PropostaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a proposta model instance should use the <code>Proposta</code> interface instead.
	 */
	public static final String TABLE_NAME = "Proposta";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"nome_completo", Types.VARCHAR},
		{"idade", Types.INTEGER}, {"sexo", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nome_completo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("idade", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("sexo", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Proposta (id_ LONG not null primary key,nome_completo VARCHAR(75) null,idade INTEGER,sexo VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table Proposta";

	public static final String ORDER_BY_JPQL = " ORDER BY proposta.id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY Proposta.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public PropostaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Proposta.class;
	}

	@Override
	public String getModelClassName() {
		return Proposta.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Proposta, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Proposta, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Proposta, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Proposta)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Proposta, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Proposta, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Proposta)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Proposta, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Proposta, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Proposta>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Proposta.class.getClassLoader(), Proposta.class,
			ModelWrapper.class);

		try {
			Constructor<Proposta> constructor =
				(Constructor<Proposta>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Proposta, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Proposta, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Proposta, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Proposta, Object>>();
		Map<String, BiConsumer<Proposta, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Proposta, ?>>();

		attributeGetterFunctions.put("id", Proposta::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<Proposta, Long>)Proposta::setId);
		attributeGetterFunctions.put(
			"nome_completo", Proposta::getNome_completo);
		attributeSetterBiConsumers.put(
			"nome_completo",
			(BiConsumer<Proposta, String>)Proposta::setNome_completo);
		attributeGetterFunctions.put("idade", Proposta::getIdade);
		attributeSetterBiConsumers.put(
			"idade", (BiConsumer<Proposta, Integer>)Proposta::setIdade);
		attributeGetterFunctions.put("sexo", Proposta::getSexo);
		attributeSetterBiConsumers.put(
			"sexo", (BiConsumer<Proposta, String>)Proposta::setSexo);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public String getNome_completo() {
		if (_nome_completo == null) {
			return "";
		}
		else {
			return _nome_completo;
		}
	}

	@Override
	public void setNome_completo(String nome_completo) {
		_nome_completo = nome_completo;
	}

	@Override
	public Integer getIdade() {
		return _idade;
	}

	@Override
	public void setIdade(Integer idade) {
		_idade = idade;
	}

	@Override
	public String getSexo() {
		if (_sexo == null) {
			return "";
		}
		else {
			return _sexo;
		}
	}

	@Override
	public void setSexo(String sexo) {
		_sexo = sexo;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Proposta.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Proposta toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Proposta>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PropostaImpl propostaImpl = new PropostaImpl();

		propostaImpl.setId(getId());
		propostaImpl.setNome_completo(getNome_completo());
		propostaImpl.setIdade(getIdade());
		propostaImpl.setSexo(getSexo());

		propostaImpl.resetOriginalValues();

		return propostaImpl;
	}

	@Override
	public int compareTo(Proposta proposta) {
		long primaryKey = proposta.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Proposta)) {
			return false;
		}

		Proposta proposta = (Proposta)obj;

		long primaryKey = proposta.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Proposta> toCacheModel() {
		PropostaCacheModel propostaCacheModel = new PropostaCacheModel();

		propostaCacheModel.id = getId();

		propostaCacheModel.nome_completo = getNome_completo();

		String nome_completo = propostaCacheModel.nome_completo;

		if ((nome_completo != null) && (nome_completo.length() == 0)) {
			propostaCacheModel.nome_completo = null;
		}

		propostaCacheModel.idade = getIdade();

		propostaCacheModel.sexo = getSexo();

		String sexo = propostaCacheModel.sexo;

		if ((sexo != null) && (sexo.length() == 0)) {
			propostaCacheModel.sexo = null;
		}

		return propostaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Proposta, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Proposta, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Proposta, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Proposta)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Proposta, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Proposta, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Proposta, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Proposta)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Proposta>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _id;
	private String _nome_completo;
	private Integer _idade;
	private String _sexo;
	private Proposta _escapedModel;

}